[package]
name = "bevy_destination_svn"
version = "0.2.0"
edition = "2021"


[dependencies]
bevy = "0.16.1"
bevy_rapier3d = "0.30.0"
rand = "0.9.1"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
