[package]
name = "bevy_destination_svn"
version = "0.2.0"
edition = "2021"


[dependencies]
bevy = "0.14.0"
bevy_rapier3d = "0.27.0"
rand = "0.8.5"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
